package com.selmec.plantaselmec.Models;
// Generated Oct 30, 2014 5:43:43 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cariles generated by hbm2java
 */
@Entity
@Table(name = "cariles", catalog = "casetapruebas")
@JsonIgnoreProperties(ignoreUnknown = true)
public class Cariles extends Equipobase implements java.io.Serializable {

    private int noCarril;
    private String planta;
    private Integer minCap;
    private Integer maxCap;
    private Set ensamblesarranques = new HashSet(0);

    public Cariles() {
    }

    @Column(name = "NoCarril", unique = true, nullable = false)
    public int getNoCarril() {
        return this.noCarril;
    }

    public void setNoCarril(int noCarril) {
        this.noCarril = noCarril;
    }

    @Column(name = "planta", unique = true, nullable = false, length = 45)
    public String getPlanta() {
        return this.planta;
    }

    public void setPlanta(String planta) {
        this.planta = planta;
    }

    @Column(name = "minCap")
    public Integer getMinCap() {
        return this.minCap;
    }

    public void setMinCap(Integer minCap) {
        this.minCap = minCap;
    }

    @Column(name = "maxCap")
    public Integer getMaxCap() {
        return this.maxCap;
    }

    public void setMaxCap(Integer maxCap) {
        this.maxCap = maxCap;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cariles")
    public Set getEnsamblesarranques() {
        return this.ensamblesarranques;
    }

    public void setEnsamblesarranques(Set ensamblesarranques) {
        this.ensamblesarranques = ensamblesarranques;
    }

}
