package com.selmec.plantaselmec.Models;
// Generated Oct 30, 2014 5:43:43 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ensamblebase generated by hbm2java
 */
@Entity
@Table(name = "ensamblebase", catalog = "casetapruebas"
)
public class Ensamblebase implements java.io.Serializable {

    private Integer id;
    private Planta planta;
    private Usuarios usuarios;
    private String folio;
    private Date dtCreacion;
    private Date dtProgramada;
    private Date dtProgramadaReal;

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

//    @ManyToOne(fetch = FetchType.LAZY)
//    @JoinColumn(name = "CarrilID", nullable = false)
//    public Cariles getCariles() {
//        return this.cariles;
//    }
//
//    public void setCariles(Cariles cariles) {
//        this.cariles = cariles;
//    }
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PlantaID", nullable = false)
    public Planta getPlanta() {
        return this.planta;
    }

    public void setPlanta(Planta planta) {
        this.planta = planta;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UsuarioID", nullable = false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    @Column(name = "folio", nullable = false, length = 50)
    public String getFolio() {
        return this.folio;
    }

    public void setFolio(String folio) {
        this.folio = folio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dtCreacion", nullable = false, length = 19)
    public Date getDtCreacion() {
        return this.dtCreacion;
    }

    public void setDtCreacion(Date dtCreacion) {
        this.dtCreacion = dtCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    public Date getDtProgramada() {
        return dtProgramada;
    }

    public void setDtProgramada(Date dtProgramada) {
        this.dtProgramada = dtProgramada;
    }

    @Temporal(TemporalType.TIMESTAMP)
    public Date getDtProgramadaReal() {
        return dtProgramadaReal;
    }

    public void setDtProgramadaReal(Date dtProgramadaReal) {
        this.dtProgramadaReal = dtProgramadaReal;
    }
}
