package com.selmec.plantaselmec.Models;
// Generated Oct 30, 2014 5:43:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Incidencias generated by hbm2java
 */
@Entity
@Table(name="incidencias"
    ,catalog="casetapruebas"
)
public class Incidencias  implements java.io.Serializable {


     private String id;
     private String descripcion;
     private Set pruebabases = new HashSet(0);

    public Incidencias() {
    }

	
    public Incidencias(String id) {
        this.id = id;
    }
    public Incidencias(String id, String descripcion, Set pruebabases) {
       this.id = id;
       this.descripcion = descripcion;
       this.pruebabases = pruebabases;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, length=45)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="Descripcion", length=250)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="incidencias")
    public Set getPruebabases() {
        return this.pruebabases;
    }
    
    public void setPruebabases(Set pruebabases) {
        this.pruebabases = pruebabases;
    }




}


