package com.selmec.plantaselmec.Models;
// Generated Oct 30, 2014 5:43:43 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Instalacion generated by hbm2java
 */
@Entity
@Table(name = "instalacion", catalog = "casetapruebas"
)
public class Instalacion extends Pruebaarranque implements java.io.Serializable {

    private boolean ventilacion;
    private boolean orientacion;
    private boolean nivel;
    private boolean silenciador;
    private boolean combustible;
    private boolean aterrizado;
    private boolean neutro;
    private boolean fuerza;
    private boolean precalentador;
    private boolean ubt;

    public Instalacion() {
    }

   
//    @OneToOne(fetch = FetchType.LAZY)
//    @PrimaryKeyJoinColumn
//    public Pruebaarranque getPruebaarranque() {
//        return this.pruebaarranque;
//    }
//
//    public void setPruebaarranque(Pruebaarranque pruebaarranque) {
//        this.pruebaarranque = pruebaarranque;
//    }

    @Column(name = "ventilacion", nullable = false)
    public boolean isVentilacion() {
        return this.ventilacion;
    }

    public void setVentilacion(boolean ventilacion) {
        this.ventilacion = ventilacion;
    }

    @Column(name = "orientacion", nullable = false)
    public boolean isOrientacion() {
        return this.orientacion;
    }

    public void setOrientacion(boolean orientacion) {
        this.orientacion = orientacion;
    }

    @Column(name = "nivel", nullable = false)
    public boolean isNivel() {
        return this.nivel;
    }

    public void setNivel(boolean nivel) {
        this.nivel = nivel;
    }

    @Column(name = "silenciador", nullable = false)
    public boolean isSilenciador() {
        return this.silenciador;
    }

    public void setSilenciador(boolean silenciador) {
        this.silenciador = silenciador;
    }

    @Column(name = "combustible", nullable = false)
    public boolean isCombustible() {
        return this.combustible;
    }

    public void setCombustible(boolean combustible) {
        this.combustible = combustible;
    }

    @Column(name = "aterrizado", nullable = false)
    public boolean isAterrizado() {
        return this.aterrizado;
    }

    public void setAterrizado(boolean aterrizado) {
        this.aterrizado = aterrizado;
    }

    @Column(name = "neutro", nullable = false)
    public boolean isNeutro() {
        return this.neutro;
    }

    public void setNeutro(boolean neutro) {
        this.neutro = neutro;
    }

    @Column(name = "fuerza", nullable = false)
    public boolean isFuerza() {
        return this.fuerza;
    }

    public void setFuerza(boolean fuerza) {
        this.fuerza = fuerza;
    }

    @Column(name = "precalentador", nullable = false)
    public boolean isPrecalentador() {
        return this.precalentador;
    }

    public void setPrecalentador(boolean precalentador) {
        this.precalentador = precalentador;
    }

    @Column(name = "ubt", nullable = false)
    public boolean isUbt() {
        return this.ubt;
    }

    public void setUbt(boolean ubt) {
        this.ubt = ubt;
    }

}
