package com.selmec.plantaselmec.Models;
// Generated Oct 29, 2014 10:37:24 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pruebabase generated by hbm2java
 */
@Entity
@Table(name = "pruebabase", catalog = "casetapruebas")
public class Pruebabase implements java.io.Serializable {

    private int id;
    private Incidencias incidencias;
    private Date dtInicio;
    private Date dtFin;
    private String comentario;
    private Set lecturases = new HashSet(0);

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "IncidenciaID", nullable = false)
    public Incidencias getIncidencias() {
        return this.incidencias;
    }

    public void setIncidencias(Incidencias incidencias) {
        this.incidencias = incidencias;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dtInicio", length = 19)
    public Date getDtInicio() {
        return this.dtInicio;
    }

    public void setDtInicio(Date dtInicio) {
        this.dtInicio = dtInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dtFin", length = 19)
    public Date getDtFin() {
        return this.dtFin;
    }

    public void setDtFin(Date dtFin) {
        this.dtFin = dtFin;
    }

    @Column(name = "comentario", length = 250)
    public String getComentario() {
        return this.comentario;
    }

    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pruebabase")
    public Set getLecturases() {
        return this.lecturases;
    }

    public void setLecturases(Set lecturases) {
        this.lecturases = lecturases;
    }

}
