package com.selmec.plantaselmec.Models;
// Generated Oct 30, 2014 5:43:43 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ubicaciones generated by hbm2java
 */
@Entity
@Table(name = "ubicaciones", catalog = "casetapruebas"
)
public class Ubicaciones implements java.io.Serializable {

    private Integer id;
    private Clientes clientes;
    private String poblacion;
    private String estado;
    private String telefono;
    private Float latitude;
    private Float longitude;
    private Set ensamblearranques = new HashSet(0);

    public Ubicaciones() {
    }

    public Ubicaciones(Clientes clientes, String poblacion, String estado, String telefono, Set ensamblearranques) {
        this.clientes = clientes;
        this.poblacion = poblacion;
        this.estado = estado;
        this.telefono = telefono;
        this.ensamblearranques = ensamblearranques;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ClienteId")
    public Clientes getClientes() {
        return this.clientes;
    }

    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

    @Column(name = "poblacion", length = 100)
    public String getPoblacion() {
        return this.poblacion;
    }

    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }

    @Column(name = "estado", length = 100)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name = "telefono", length = 45)
    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ubicaciones")
    public Set getEnsamblearranques() {
        return this.ensamblearranques;
    }

    public void setEnsamblearranques(Set ensamblearranques) {
        this.ensamblearranques = ensamblearranques;
    }

    @Column(name = "latitude")
    public Float getLatitude() {
        return this.latitude;
    }

    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }
    
    @Column(name = "longitude")
    public Float getLongitude() {
        return this.longitude;
    }

    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

}
